source :rubygems

gem "activemodel"
gem "activerecord"
gem "activesupport"
gem "arel"
gem "bcrypt-ruby", "~> 3.0.1"
gem "builder", "~> 3.0.0"
gem "diff-lcs", "~> 1.1.3"
gem "i18n"
gem "innate", "~> 2011.04"
gem "multi_json", "~> 1.0.3"
gem "rack"
gem "rake"
gem "ramaze", "~> 2011.07.25"
gem "rdoc"
gem "rspec", "~> 2.6.0"
gem "rspec-core", "~> 2.6.4"
gem "rspec-expectations", "~> 2.6.0"
gem "rspec-mocks", "~> 2.6.0"
gem "sqlite3"
gem "tzinfo"
