source :rubygems

gem "activemodel"
gem "activerecord"
gem "activesupport"
gem "arel"
gem "bcrypt"
gem "builder"
gem "diff-lcs"
gem "i18n"
gem "innate"
gem "multi_json"
gem "rack", "~> 1.4.0"
gem "rake"
gem "ramaze"
gem "rdoc"
gem "rspec"
gem "rspec-core"
gem "rspec-expectations"
gem "rspec-mocks"
gem "sqlite3"
gem "tzinfo"
